version: '3'
services:
  tekxit:
    build:
      context: .
      args:
        VERSION: 0.32.0
    environment:
      - JAVA_XMS=4G
      - JAVA_XMX=12G
    ports:
      - 25565:25565
    volumes:
      - ./data:/data
