name: build

on:
  push:
    branches:
      - "master"
    tags:
      - '*'
  pull_request:

permissions:
  contents: write
  packages: write

jobs:
  docker:
    name: Build and publish Docker images
    runs-on: ubuntu-latest
    env:
      VERSION: 0.32.0
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/Ithilias/minecraft-tekxit4-docker
          tags: |
            type=raw,value=${{ env.VERSION }}
            type=raw,value=latest

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and publish image
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: ${{ github.event.pull_request.head.repo.full_name == 'Ithilias/minecraft-tekxit4-docker' || github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILDTIME=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}
            REVISION=${{ github.event.pull_request.head.sha }}
            VERSION=${{ env.VERSION }}
          cache-to: type=gha
          cache-from: type=gha

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
