name: Tekxit4 Version Auto-Updater

on:
  schedule:
    - cron: '5 2 * * *'

permissions:
  contents: write
  packages: write

jobs:
  update-tekxit-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Current Version
        run: echo "CURRENT_VERSION=$(grep -oP '(?<=\bVERSION=")[^"]+' ./Dockerfile)" >> $GITHUB_ENV

      - name: Print Stored Version Number
        run: echo ${{ env.CURRENT_VERSION }}

      - name: Get Repository Version
        run: echo "REPO_VERSION=$(curl -sL https://api.technicpack.net/modpack/tekxit-4-official?build=latest | jq -r ".version")" >> $GITHUB_ENV

      - name: Print Repository Version
        run: echo ${{ env.REPO_VERSION }}

      - name: Update Dockerfile Version
        if: ${{ env.CURRENT_VERSION != env.REPO_VERSION }}
        run: sed -i "s/${{ env.CURRENT_VERSION }}/${{ env.REPO_VERSION }}/" ./Dockerfile

      - name: Login to GitHub Container Registry
        if: ${{ env.CURRENT_VERSION != env.REPO_VERSION }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        if: ${{ env.CURRENT_VERSION != env.REPO_VERSION }}
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=${{ env.REPO_VERSION }}
            type=raw,value=latest

      - name: Set up QEMU
        if: ${{ env.CURRENT_VERSION != env.REPO_VERSION }}
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: ${{ env.CURRENT_VERSION != env.REPO_VERSION }}
        uses: docker/setup-buildx-action@v3

      - name: Build and publish image
        if: ${{ env.CURRENT_VERSION != env.REPO_VERSION }}
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILDTIME=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}
            REVISION=${{ github.sha }}
            VERSION=${{ env.REPO_VERSION }}
          cache-to: type=gha
          cache-from: type=gha

      - name: Image digest
        if: ${{ env.CURRENT_VERSION != env.REPO_VERSION }}
        run: echo ${{ steps.docker_build.outputs.digest }}

      - uses: stefanzweifel/git-auto-commit-action@v5
        if: ${{ env.CURRENT_VERSION != env.REPO_VERSION }}
        with:
          commit_message: "Github Action: Updating to Tekxit version ${{ env.REPO_VERSION }}"
          commit_options: '--no-verify --signoff'
          repository: .
          tagging_message: '${{ env.REPO_VERSION }}'
          skip_fetch: true
          skip_checkout: true
          create_branch: false